{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "northwatch.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "northwatch.labels" . | nindent 4 }}
{{- end -}}
